<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OtherUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rule = [
            [
                'id_number' => '420127945',
                'name' => 'BASILISCO,GEMS ELFORD G.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131459',
                'name' => 'BESARIO,AUGUSTEN D.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131514',
                'name' => 'CABAÑOG,JUNAZETTE A.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131469',
                'name' => 'CANILLO,CHRISTIAN C.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131406',
                'name' => 'CARACENA,ARLAN G.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420130783',
                'name' => 'DUMOGHO,LEONARD T.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131405',
                'name' => 'EDULLANTES,JOHN LORENCE S.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420130222',
                'name' => 'ENARDECIDO,ROBERTO T.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131330',
                'name' => 'FULGO,JAMAICA D.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131620',
                'name' => 'GARNICA,ANA MARIE C.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131493',
                'name' => 'LEGASPI,ROSALIA L.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131633',
                'name' => 'LIBRADILLA,MERY JOY C.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131869',
                'name' => 'MANINGO,ANGELOU V.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131692',
                'name' => 'MANZAN,ANGELICA S.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131472',
                'name' => 'MONTES,JOHN PAUL T.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131867',
                'name' => 'PABADORA,WEJIE T.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131621',
                'name' => 'PERAL,JUDE A.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131617',
                'name' => 'PLACIA,MARIEL B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131630',
                'name' => 'TACULOY,JANICE A.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131599',
                'name' => 'TIGRES,JESSAMAR B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131629',
                'name' => 'TOMAQUIN,CHERILYN C.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131855',
                'name' => 'UNDONA,JUVY ANN V.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420132801',
                'name' => 'WOO,LLOYD KENNETH N.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131464',
                'name' => 'ADIONG,JARIE ANN',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131875',
                'name' => 'ALVAREZ,MELBERT B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131460',
                'name' => 'AMAD,CARLA',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131866',
                'name' => 'BACANE,ANALIZA D.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131862',
                'name' => 'BANDICO,ANA GRACE P.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131366',
                'name' => 'BARCENAL,STEPHANIE MAY',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420124094',
                'name' => 'BARILLO,VENNY KRISTOFFER T.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131355',
                'name' => 'BEDIO,JURALYN M.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131326',
                'name' => 'BLANCO,APRILYN B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131371',
                'name' => 'BOLHANO,JEFF',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131336',
                'name' => 'BUBOLE,LIESA',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131856',
                'name' => 'BULADO,JOSEPH C.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420130312',
                'name' => 'CASIPONG,CHRISTINE FAITH V.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131872',
                'name' => 'CATUBAY,GENESA D.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131480',
                'name' => 'CAÑASARES,JASMIN FE A.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131346',
                'name' => 'CAÑETE,JEREMAE L.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420128988',
                'name' => 'DEPILLO,JANAH E.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131526',
                'name' => 'ENERLAN,CHRISTELYN FAITH B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131598',
                'name' => 'GENELIA,ROBERT E.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131694',
                'name' => 'HAGNAYA,ARNOLD M.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131384',
                'name' => 'PEQUE,JIMER S.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131592',
                'name' => 'QUILLANO,ANGEL R.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420129071',
                'name' => 'TAMPARONG,RUTH',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131503',
                'name' => 'ACABAL,GLENN MIKE B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131317',
                'name' => 'ALBORES,FRIENCIL JAE G.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131747',
                'name' => 'BIANGOS,JHUN EMMANUEL',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131392',
                'name' => 'BIGTASIN,CLIFFJOHN',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131333',
                'name' => 'BONGANCISO,GLEVIN B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131431',
                'name' => 'COBRE,JOHNNELYN D.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131520',
                'name' => 'DE ASIS,JUVY P.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131521',
                'name' => 'DIVINAGRACIA,JUNE DEL B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131450',
                'name' => 'DOLLENTE,ARIANE A.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131442',
                'name' => 'DORIO,KYLA MAE M.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131416',
                'name' => 'ENOSTACION,ROMAR ANGELU J.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131349',
                'name' => 'GARGANIAN,REYMART B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131533',
                'name' => 'GENEMILO,GENEVA G.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131623',
                'name' => 'JIMENEZ,RICHARD O.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131643',
                'name' => 'LIMBAGA,JUSTINE M.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131690',
                'name' => 'MACALUA,KATRINA E.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131595',
                'name' => 'OBIDAS,MARICON Y.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131376',
                'name' => 'PEQUE,CEJIE S.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131586',
                'name' => 'RONDUBIO,CLART A.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131809',
                'name' => 'SAME,QUINGEI B.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131594',
                'name' => 'SARTAGODA,JOHN CARLOU T.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131602',
                'name' => 'UNABIA,JOHN CARLOU LEOPOLD J.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],
            [
                'id_number' => '420131635',
                'name' => 'YCOT,JOHN JHAPHER L.',
                'email' => 'student@gmail.com',
                'phone_number' => '9212969669',
                'password' => bcrypt('student123'),
                'rule_id' => 3,
                'course_id' => 5,
            ],

        ];

        User::insert($rule);
    }
}
