<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rule = [
            [ 
            'id_number' => '1234567',
            'name' => 'Admin',
            'email' => 'admin@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('admin123'),
            'rule_id' => 1,
            'course_id' => null,
            ],
            [ 
            'id_number' => '2019LGD129G',
            'name' => 'Lezel G. Dagudog',
            'email' => 'instructor@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('instructor123'),
            'rule_id' => 2,
            'course_id' => null,
            ],
            [ 
            'id_number' => '2023WFV00817',
            'name' => 'William F. Vidal',
            'email' => 'william@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('william123'),
            'rule_id' => 2,
            'course_id' => null,
            ],
            
            //for student
            [ 
            'id_number' => '12345679',
            'name' => 'Student',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132646',
            'name' => 'AMPALAYOHAN,ZENELOS F.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132587',
            'name' => 'APATAN,RHEA KRISELLE C.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132723',
            'name' => 'BRADY,RHONA MAE G. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132582',
            'name' => 'CAMANZO,ANGELYN P. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132589',
            'name' => 'CASIPONG,ANALYN A. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132660',
            'name' => 'DENOLAN,AIZA M.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132667',
            'name' => 'EDGAN,TESSA MAE L.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132642',
            'name' => 'ESCONDE,JOYCE NIÃ±A A. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132662',
            'name' => 'ESTRADA,JAY LORD P.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132566',
            'name' => 'GEORPE,AILENE A.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132982',
            'name' => 'GIMENA,JONEL L.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132617',
            'name' => 'GUIPE,MARK SIDRO M.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132670',
            'name' => 'LIM,MARIE JANE D.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132595',
            'name' => 'NICOR,MA. VERNA G.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132577',
            'name' => 'OLA-A,MAUREEN GLYZE O.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132719',
            'name' => 'ORELLANO,RONEL FRANCIS L.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132712',
            'name' => 'PATACSIL,JOHNZEN P. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132609',
            'name' => 'PEÃ±ONAL,MA. MAE P.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132624',
            'name' => 'PUN-AN,NEIL PAOLO A.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132615',
            'name' => 'REDOBLADO,LOVELY CHARS C.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132572',
            'name' => 'SUMUGAT,JUNRYLL B',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132721',
            'name' => 'VERGARA,DAVE KHENT T.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132603',
            'name' => 'VILLAMIL,STEPHANIE KATE P.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132633',
            'name' => 'VILLASEÃ±OR,CHRISTIAN C.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132990',
            'name' => 'ZARATE,ROLLIE HAMILTON T.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            // [
            //     'id_number' => '202200005',
            //     'name' => 'AMBOS,CORDEL MARK V.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3
            // ],
            // [
            //     'id_number' => '202100054',
            //     'name' => 'ANGCA,CRISTINE A.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3
            // ],
            // [
            //     'id_number' => '202100304',
            //     'name' => 'BALDADO,JIADON T.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100060',
            //     'name' => 'BAYAWA,JASHEL O.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202000325',
            //     'name' => 'CABUAL,CLIFF A.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100080',
            //     'name' => 'CABUNTAL,ERNILYN M.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100086',
            //     'name' => 'CARLOS,JAIME D.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100098',
            //     'name' => 'DELA CRUZ,MARY ROSE C.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100105',
            //     'name' => 'DIACOSA,JOHN MARK M.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100118',
            //     'name' => 'EWAYAN,LANI ROSE E.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100301',
            //     'name' => 'FACTURAN,JOHN KURT R.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100127',
            //     'name' => 'GOMEZ,HANNIE MAE P.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100135',
            //     'name' => 'KADUSALE,JUPHIL B.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100146',
            //     'name' => 'LAGUNERO,KHYRA JEAN C.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100192',
            //     'name' => 'ORTEGA,JONARD ANGEL A.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100201',
            //     'name' => 'PETILUNA,TRISHA MAE P.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100318',
            //     'name' => 'RAMIREZ,JESSA A.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100423',
            //     'name' => 'SANTIAGO,ROLLY R.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '201900024',
            //     'name' => 'SARTAGODA,CHRISTINE JOY P.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
            // [
            //     'id_number' => '202100208',
            //     'name' => 'SENILLO,IAN M.',
            //     'email' => 'student@gmail.com',
            //     'phone_number' => '9212969669',
            //     'password' => bcrypt('student123'),
            //     'rule_id' => 3,
            //     'course_id' => 3,
            // ],
        ];

        User::insert($rule);
    }
}
