<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $rule = [
            [ 
            'id_number' => '1234567',
            'name' => 'Admin',
            'email' => 'admin@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('admin123'),
            'rule_id' => 1,
            'course_id' => null,
            ],
            [ 
            'id_number' => '2019LGD129G',
            'name' => 'Lezel G. Dagudog',
            'email' => 'instructor@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('instructor123'),
            'rule_id' => 2,
            'course_id' => null,
            ],
            
            //for student
            [ 
            'id_number' => '12345679',
            'name' => 'Student',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132646',
            'name' => 'AMPALAYOHAN,ZENELOS F.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132587',
            'name' => 'APATAN,RHEA KRISELLE C.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132723',
            'name' => 'BRADY,RHONA MAE G. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132582',
            'name' => 'CAMANZO,ANGELYN P. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132589',
            'name' => 'CASIPONG,ANALYN A. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132660',
            'name' => 'DENOLAN,AIZA M.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132667',
            'name' => 'EDGAN,TESSA MAE L.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132642',
            'name' => 'ESCONDE,JOYCE NIÃ±A A. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132662',
            'name' => 'ESTRADA,JAY LORD P.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132566',
            'name' => 'GEORPE,AILENE A.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132982',
            'name' => 'GIMENA,JONEL L.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132617',
            'name' => 'GUIPE,MARK SIDRO M.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132670',
            'name' => 'LIM,MARIE JANE D.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132595',
            'name' => 'NICOR,MA. VERNA G.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132577',
            'name' => 'OLA-A,MAUREEN GLYZE O.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132719',
            'name' => 'ORELLANO,RONEL FRANCIS L.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132712',
            'name' => 'PATACSIL,JOHNZEN P. ',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132609',
            'name' => 'PEÃ±ONAL,MA. MAE P.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132624',
            'name' => 'PUN-AN,NEIL PAOLO A.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132615',
            'name' => 'REDOBLADO,LOVELY CHARS C.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132572',
            'name' => 'SUMUGAT,JUNRYLL B',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132721',
            'name' => 'VERGARA,DAVE KHENT T.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132603',
            'name' => 'VILLAMIL,STEPHANIE KATE P.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132633',
            'name' => 'VILLASEÃ±OR,CHRISTIAN C.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
            [ 
            'id_number' => '420132990',
            'name' => 'ZARATE,ROLLIE HAMILTON T.',
            'email' => 'student@gmail.com',
            'phone_number' => '9212969669',
            'password' => bcrypt('student123'),
            'rule_id' => 3,
            'course_id' => 5,
            ],
        ];

        User::insert($rule);
    }
}
